SERVICES = {
  'vm1' => {
    ip: '192.168.56.2',
  },
  'vm2' => {
    ip_network_a: '192.168.56.1',
    ip_network_b: '192.168.57.1'
  },
  'vm3' => {
    ip: '192.168.57.2',
  }
}


Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.provision "shell", inline: "sudo chsh -s /bin/bash vagrant"

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: SERVICES['vm1'][:ip]
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: SERVICES['vm2'][:ip_network_a]
    vm2.vm.network "private_network", ip: SERVICES['vm2'][:ip_network_b]
  end
  
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: SERVICES['vm3'][:ip]
  end
end
