SERVICES = {
  'vm1' => {
    ip: '192.168.56.2',
  },
  'vm2' => {
    ip_network_a: '192.168.56.1',
    ip_network_b: '192.168.57.1'
  },
  'vm3' => {
    ip: '192.168.57.2',
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  config.vm.provision "shell", inline: "sudo chsh -s /bin/bash vagrant"

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: SERVICES['vm1'][:ip]
    
    vm1.vm.provision "shell", inline: <<-SHELL
      echo "#{SERVICES['vm2'][:ip_network_a]} vm2" | sudo tee -a /etc/hosts
      echo "#{SERVICES['vm3'][:ip]} vm3" | sudo tee -a /etc/hosts
    SHELL

    vm1.vm.provision "shell", inline: "sudo ip route add 192.168.57.0/24 via #{SERVICES['vm2'][:ip_network_a]}"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: SERVICES['vm2'][:ip_network_a]
    vm2.vm.network "private_network", ip: SERVICES['vm2'][:ip_network_b]
    
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo sysctl -w net.ipv4.ip_forward=1
      echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/99-routing.conf
    SHELL

    vm2.vm.provision "shell", inline: <<-SHELL
      echo "#{SERVICES['vm1'][:ip]} vm1" | sudo tee -a /etc/hosts
      echo "#{SERVICES['vm3'][:ip]} vm3" | sudo tee -a /etc/hosts
    SHELL
  end

  
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: SERVICES['vm3'][:ip]

    vm3.vm.provision "shell", inline: <<-SHELL
      echo "#{SERVICES['vm1'][:ip]} vm1" | sudo tee -a /etc/hosts
      echo "#{SERVICES['vm2'][:ip_network_b]} vm2" | sudo tee -a /etc/hosts
    SHELL

    
    vm3.vm.provision "shell", inline: "sudo ip route add 192.168.56.0/24 via #{SERVICES['vm2'][:ip_network_b]}"
  end
end
