Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"

  config.vm.provider "virtualbox" do |vb|
    # Définir la mémoire vive en Mo
    vb.memory = "2048"
    # Modifier aussi le nombre de processeurs
    vb.cpus = 2
  end

  config.vm.provision "shell", 
    inline: <<-SHELL
              sudo apt-get update
              sudo apt-get install -y vim net-tools dnsutils
            SHELL

end
