SERVICES = {
  'vm1' => {
    ip: '192.168.62.1',
  },
  'vm2' => {
    ip: '192.168.62.2',
  }
}


Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  config.vm.provision "shell", inline: "sudo chsh -s /bin/bash vagrant"
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: SERVICES['vm1'][:ip]
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: SERVICES['vm2'][:ip]
  end

end
